runtime: nodejs
env: flex
#service: cloud-hive

automatic_scaling:
  max_num_instances: 1

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

skip_files:
  - ^components$
  - ^pages$
  - ^server$
  - ^utils$
  - ^store$
  - ^\.idea$